// Code generated by protoc-gen-go.
// source: protos/golang.conradwood.net/apis/protorenderer2/protorenderer2.proto
// DO NOT EDIT!

/*
Package protorenderer2 is a generated protocol buffer package.

It is generated from these files:
	protos/golang.conradwood.net/apis/protorenderer2/protorenderer2.proto

It has these top-level messages:
	ProtocRequest
	FileTransfer
*/
package protorenderer2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import protorenderer "golang.conradwood.net/apis/protorenderer"
import common "golang.conradwood.net/apis/common"
import _ "golang.conradwood.net/apis/h2gproxy"
import google_protobuf "github.com/golang/protobuf/protoc-gen-go/descriptor"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProtocRequest struct {
	VerifyToken string                                 `protobuf:"bytes,1,opt,name=VerifyToken" json:"VerifyToken,omitempty"`
	ProtoFiles  []*google_protobuf.FileDescriptorProto `protobuf:"bytes,2,rep,name=ProtoFiles" json:"ProtoFiles,omitempty"`
}

func (m *ProtocRequest) Reset()                    { *m = ProtocRequest{} }
func (m *ProtocRequest) String() string            { return proto.CompactTextString(m) }
func (*ProtocRequest) ProtoMessage()               {}
func (*ProtocRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ProtocRequest) GetVerifyToken() string {
	if m != nil {
		return m.VerifyToken
	}
	return ""
}

func (m *ProtocRequest) GetProtoFiles() []*google_protobuf.FileDescriptorProto {
	if m != nil {
		return m.ProtoFiles
	}
	return nil
}

type FileTransfer struct {
	Filename         string `protobuf:"bytes,1,opt,name=Filename" json:"Filename,omitempty"`
	Data             []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	TransferComplete bool   `protobuf:"varint,3,opt,name=TransferComplete" json:"TransferComplete,omitempty"`
}

func (m *FileTransfer) Reset()                    { *m = FileTransfer{} }
func (m *FileTransfer) String() string            { return proto.CompactTextString(m) }
func (*FileTransfer) ProtoMessage()               {}
func (*FileTransfer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FileTransfer) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *FileTransfer) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *FileTransfer) GetTransferComplete() bool {
	if m != nil {
		return m.TransferComplete
	}
	return false
}

func init() {
	proto.RegisterType((*ProtocRequest)(nil), "protorenderer2.ProtocRequest")
	proto.RegisterType((*FileTransfer)(nil), "protorenderer2.FileTransfer")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ProtoRenderer2 service

type ProtoRenderer2Client interface {
	// protoc-gen-meta2 submits files to protorenderer server for analysis
	SubmitSource(ctx context.Context, in *ProtocRequest, opts ...grpc.CallOption) (*common.Void, error)
	// compile
	Compile(ctx context.Context, opts ...grpc.CallOption) (ProtoRenderer2_CompileClient, error)
	// add or update a ".proto" file in the renderers database
	UpdateProto(ctx context.Context, in *protorenderer.AddProtoRequest, opts ...grpc.CallOption) (*protorenderer.AddProtoResponse, error)
}

type protoRenderer2Client struct {
	cc *grpc.ClientConn
}

func NewProtoRenderer2Client(cc *grpc.ClientConn) ProtoRenderer2Client {
	return &protoRenderer2Client{cc}
}

func (c *protoRenderer2Client) SubmitSource(ctx context.Context, in *ProtocRequest, opts ...grpc.CallOption) (*common.Void, error) {
	out := new(common.Void)
	err := grpc.Invoke(ctx, "/protorenderer2.ProtoRenderer2/SubmitSource", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protoRenderer2Client) Compile(ctx context.Context, opts ...grpc.CallOption) (ProtoRenderer2_CompileClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ProtoRenderer2_serviceDesc.Streams[0], c.cc, "/protorenderer2.ProtoRenderer2/Compile", opts...)
	if err != nil {
		return nil, err
	}
	x := &protoRenderer2CompileClient{stream}
	return x, nil
}

type ProtoRenderer2_CompileClient interface {
	Send(*FileTransfer) error
	Recv() (*FileTransfer, error)
	grpc.ClientStream
}

type protoRenderer2CompileClient struct {
	grpc.ClientStream
}

func (x *protoRenderer2CompileClient) Send(m *FileTransfer) error {
	return x.ClientStream.SendMsg(m)
}

func (x *protoRenderer2CompileClient) Recv() (*FileTransfer, error) {
	m := new(FileTransfer)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *protoRenderer2Client) UpdateProto(ctx context.Context, in *protorenderer.AddProtoRequest, opts ...grpc.CallOption) (*protorenderer.AddProtoResponse, error) {
	out := new(protorenderer.AddProtoResponse)
	err := grpc.Invoke(ctx, "/protorenderer2.ProtoRenderer2/UpdateProto", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ProtoRenderer2 service

type ProtoRenderer2Server interface {
	// protoc-gen-meta2 submits files to protorenderer server for analysis
	SubmitSource(context.Context, *ProtocRequest) (*common.Void, error)
	// compile
	Compile(ProtoRenderer2_CompileServer) error
	// add or update a ".proto" file in the renderers database
	UpdateProto(context.Context, *protorenderer.AddProtoRequest) (*protorenderer.AddProtoResponse, error)
}

func RegisterProtoRenderer2Server(s *grpc.Server, srv ProtoRenderer2Server) {
	s.RegisterService(&_ProtoRenderer2_serviceDesc, srv)
}

func _ProtoRenderer2_SubmitSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProtocRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoRenderer2Server).SubmitSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protorenderer2.ProtoRenderer2/SubmitSource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoRenderer2Server).SubmitSource(ctx, req.(*ProtocRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtoRenderer2_Compile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProtoRenderer2Server).Compile(&protoRenderer2CompileServer{stream})
}

type ProtoRenderer2_CompileServer interface {
	Send(*FileTransfer) error
	Recv() (*FileTransfer, error)
	grpc.ServerStream
}

type protoRenderer2CompileServer struct {
	grpc.ServerStream
}

func (x *protoRenderer2CompileServer) Send(m *FileTransfer) error {
	return x.ServerStream.SendMsg(m)
}

func (x *protoRenderer2CompileServer) Recv() (*FileTransfer, error) {
	m := new(FileTransfer)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ProtoRenderer2_UpdateProto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(protorenderer.AddProtoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoRenderer2Server).UpdateProto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protorenderer2.ProtoRenderer2/UpdateProto",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoRenderer2Server).UpdateProto(ctx, req.(*protorenderer.AddProtoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProtoRenderer2_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protorenderer2.ProtoRenderer2",
	HandlerType: (*ProtoRenderer2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitSource",
			Handler:    _ProtoRenderer2_SubmitSource_Handler,
		},
		{
			MethodName: "UpdateProto",
			Handler:    _ProtoRenderer2_UpdateProto_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Compile",
			Handler:       _ProtoRenderer2_Compile_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "protos/golang.conradwood.net/apis/protorenderer2/protorenderer2.proto",
}

func init() {
	proto.RegisterFile("protos/golang.conradwood.net/apis/protorenderer2/protorenderer2.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 383 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x53, 0x4f, 0xef, 0x93, 0x40,
	0x10, 0x0d, 0xad, 0xd1, 0xba, 0xc5, 0xc6, 0xec, 0x89, 0x10, 0xff, 0x90, 0xc6, 0x03, 0xf5, 0xb0,
	0x18, 0x3c, 0xea, 0x45, 0xad, 0x26, 0x5e, 0x8c, 0xa1, 0xb5, 0x07, 0x6f, 0x5b, 0x76, 0x8a, 0x28,
	0xec, 0xe0, 0xee, 0x92, 0xda, 0x6f, 0xec, 0xc7, 0x30, 0xc0, 0xb6, 0x01, 0xcc, 0xaf, 0xe9, 0x89,
	0x79, 0x33, 0xf3, 0xe6, 0x3d, 0x98, 0x81, 0x7c, 0xac, 0x14, 0x1a, 0xd4, 0x51, 0x86, 0x05, 0x97,
	0x19, 0x4b, 0x51, 0x2a, 0x2e, 0x8e, 0x88, 0x82, 0x49, 0x30, 0x11, 0xaf, 0x72, 0x1d, 0xb5, 0x1d,
	0x0a, 0xa4, 0x00, 0x05, 0x2a, 0x1e, 0x41, 0xd6, 0x42, 0xba, 0x18, 0x66, 0xfd, 0xb7, 0xb7, 0xce,
	0x1b, 0xa2, 0x6e, 0x9a, 0xcf, 0xae, 0xb0, 0x53, 0x2c, 0x4b, 0x94, 0xf6, 0x61, 0xfb, 0xe3, 0x2b,
	0xfd, 0x3f, 0xe2, 0xac, 0x52, 0xf8, 0xe7, 0x74, 0x09, 0x2c, 0x27, 0xc8, 0x10, 0xb3, 0x02, 0x3a,
	0xfd, 0x7d, 0x7d, 0x88, 0x04, 0xe8, 0x54, 0xe5, 0x95, 0x41, 0xeb, 0x62, 0x79, 0x24, 0x8f, 0xbe,
	0x36, 0x41, 0x9a, 0xc0, 0xef, 0x1a, 0xb4, 0xa1, 0x01, 0x99, 0xef, 0x40, 0xe5, 0x87, 0xd3, 0x16,
	0x7f, 0x81, 0xf4, 0x9c, 0xc0, 0x09, 0x1f, 0x26, 0xfd, 0x14, 0x5d, 0x13, 0xd2, 0x52, 0x3e, 0xe5,
	0x05, 0x68, 0x6f, 0x12, 0x4c, 0xc3, 0x79, 0xfc, 0x82, 0x75, 0x4a, 0xec, 0xac, 0xc4, 0x9a, 0xea,
	0xfa, 0xa2, 0xd6, 0x12, 0x92, 0x1e, 0x6f, 0xf9, 0x93, 0xb8, 0x4d, 0xb0, 0x55, 0x5c, 0xea, 0x03,
	0x28, 0xea, 0x93, 0x59, 0x83, 0x25, 0x2f, 0xc1, 0x8a, 0x5e, 0x30, 0xa5, 0xe4, 0xde, 0x9a, 0x1b,
	0xee, 0x4d, 0x02, 0x27, 0x74, 0x93, 0x36, 0xa6, 0x2f, 0xc9, 0xe3, 0x33, 0xf7, 0x03, 0x96, 0x55,
	0x01, 0x06, 0xbc, 0x69, 0xe0, 0x84, 0xb3, 0xe4, 0xbf, 0x7c, 0xfc, 0xd7, 0x21, 0x8b, 0xce, 0xc1,
	0x79, 0x77, 0xf4, 0x0d, 0x71, 0x37, 0xf5, 0xbe, 0xcc, 0xcd, 0x06, 0x6b, 0x95, 0x02, 0x7d, 0xca,
	0x46, 0x2b, 0x1f, 0x7c, 0x15, 0xdf, 0x65, 0x76, 0x17, 0x3b, 0xcc, 0x05, 0xfd, 0x4c, 0x1e, 0x34,
	0xb3, 0xf3, 0x02, 0xe8, 0x93, 0x31, 0xaf, 0xff, 0x52, 0xfe, 0xd5, 0x6a, 0xe8, 0xbc, 0x72, 0xe8,
	0x17, 0x32, 0xff, 0x56, 0x09, 0x6e, 0xa0, 0xd5, 0xa3, 0xcf, 0x86, 0x04, 0xf6, 0x4e, 0x08, 0x6b,
	0xbc, 0xf3, 0xf1, 0xfc, 0xce, 0xba, 0xae, 0x50, 0x6a, 0x78, 0xbf, 0x23, 0x2b, 0x09, 0xa6, 0x7f,
	0x24, 0xf6, 0x6c, 0x9a, 0x3b, 0x19, 0xb9, 0xf9, 0xbe, 0xba, 0xf9, 0x87, 0xd8, 0xdf, 0x6f, 0xf1,
	0xeb, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x61, 0xab, 0x4a, 0x69, 0x4b, 0x03, 0x00, 0x00,
}
